region_detector_node:
  ros__parameters:
    lookahead_distance: 0.5
    publish_rate: 20.0
    fluctuate_region_1: [-0.05, -0.83, -1.8, -1.8, -1.35, -3.0, 0.78, -2.0]
    fluctuate_region_1_yaw: 0.0
    fluctuate_region_2: [0.0]
    fluctuate_region_2_yaw: 0.0
    fluctuate_region_3: [0.0]
    fluctuate_region_3_yaw: 0.0
