/**:
    ros__parameters:

        use_imu_as_input: False
        prop_at_freq_of_imu: True
        check_satu: True
        init_map_size: 10
        point_filter_num: 3
        space_down_sample: True
        filter_size_surf: 0.2
        filter_size_map: 0.2
        ivox_nearby_type: 6
        runtime_pos_log_enable: False

        common:
            lid_topic: "livox/lidar"
            imu_topic: "livox/imu"
            con_frame: False
            con_frame_num: 1
            cut_frame: False
            cut_frame_time_interval: 0.1
            time_diff_lidar_to_imu: 0.0

        preprocess:
            lidar_type: 1
            scan_line: 4
            timestamp_unit: 1
            blind: 0.5

        mapping:
            imu_en: True
            extrinsic_est_en: False
            imu_time_inte: 0.005
            lidar_time_inte: 0.1
            satu_acc: 3.0
            satu_gyro: 35.0
            acc_norm: 1.0
            lidar_meas_cov: 0.01
            acc_cov_output: 500.0
            gyr_cov_output: 1000.0
            b_acc_cov: 0.0001
            b_gyr_cov: 0.0001
            imu_meas_acc_cov: 0.01
            imu_meas_omg_cov: 0.01
            gyr_cov_input: 0.01
            acc_cov_input: 0.1
            plane_thr: 0.1
            match_s: 81.0
            ivox_grid_resolution: 0.5
            gravity: [ 0.0, 0.0, -9.810 ]
            gravity_init: [ 0.0, 0.0, -9.810 ]
            extrinsic_T: [ -0.011, -0.02329, 0.04412 ]
            extrinsic_R: [ 1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0 ]

        odometry:
            publish_odometry_without_downsample: False

        publish:
            path_en: True
            scan_publish_en: True
            scan_bodyframe_pub_en: False
            tf_send_en: True

        pcd_save:
            pcd_save_en: True
            interval: -1

